-- execute like 50 times
-- original post: https://scriptblox.com/script/Universal-Script-Lag-script-for-Kurdish-obby-75631
-- original owner: https://scriptblox.com/u/Mhammadaram1213
-- original pastebin url: https://pastebin.com/raw/MQc6KCKF
-- game: https://www.roblox.com/games/131981556501504/Kurdish-Obbyy
while task.wait() do
	game:GetService("ReplicatedStorage"):WaitForChild("ChatEvent"):FireServer("aajajajajajajajajajajajajakajjaajajakjajajajajajajaa")
end
